# question_data = [
# {"text": "A slug's blood is green.", "answer": "True"},
# {"text": "The loudest animal is the African Elephant.", "answer": "False"},
# {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
# {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
# {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
# {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
# {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
# {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
# {"text": "Google was originally called 'Backrub'.", "answer": "True"},
# {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
# {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
# {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = [
    {"text": "A bird in the hand is worth two in the bush.", "answer": "True"},
    {"text": "The opposite sides of a dice always add up to 7.", "answer": "True"},
    {"text": "All cacti are succulents.", "answer": "True"},
    {"text": "A square has more sides than a triangle.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "A tomato is a fruit.", "answer": "True"},
    {"text": "The sun rises in the west.", "answer": "False"},
    {"text": "Sound travels faster through water than through air.", "answer": "True"},
    {"text": "A triangle always has one right angle.", "answer": "False"},
    {"text": "The moon is larger than Earth.", "answer": "False"},
    {"text": "Goldfish have a three-second memory.", "answer": "False"},
    {"text": "Spiders are insects.", "answer": "False"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "A kilometer is longer than a mile.", "answer": "False"},
    {"text": "Cows can walk downstairs but not upstairs.", "answer": "False"},
    {"text": "A snail can sleep for three years.", "answer": "False"},
    {
        "text": "The Statue of Liberty was a gift from France to the United States.",
        "answer": "True",
    },
    {"text": "An ostrich can fly.", "answer": "False"},
    {"text": "The human body has 206 bones.", "answer": "True"},
]
